### ISSUE TITLE
Plugin should add permissions automatically and other improvements

### ISSUE THREAD

**Issue by HyperBrain** [rifflock/serverless-logstreaming-plugin#1]
Currently the user is forced to add the loghandler permissions in the resources section of the serverless.yml.
```yaml
# serverless.yml
resources:
  Resources:
    LoggingLambdaPermission:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName:
          Ref: LoghandlerLambdaFunction
        Action: lambda:InvokeFunction
        Principal: logs.amazonaws.com
```

This is very error-prone and could be done automatically by the plugin. To make this work, the loghandler function should be defined in a separate configuration section for the plugin:

```yaml
# serverless.yml
custom:
  logHandler:
    function: myLogHandlerFunction    # Declares the loghandler of the service
```

Additionally a configuration per function would be extremely nice. Usually not every function in a service is needed to be attached to the loghandler. A flag should be introduced, that allows Serverless functions to be excluded from the loghandler functionality (or excluded, depending if a whitelist or blacklist pattern would make more sense).

Sample:
```yaml
# serverless.yml
functions:
  myFunc1:
    handler: src/myfunc1.handle
    logHandler: false    # Would exclude the function from loghandling
```
